flags:
  feature1: true
  feature2: true

scheduler:
  bill_generation: "1 5 6 4"
  account_state: "6 3 4 8"

nested:
  level1:
    level11: 800
  level2:
    level21: 900
  level3:
    level31:
      level 311: 1000
