flags:
  feature1: false
  feature2: true

scheduler:
  bill_generation: "1 2 3 4"
  account_state: "6 3 4 5"

nested:
  level1:
    level11: 30
  level2:
    level21: 40
  level3:
    level31:
      level 311: 50
