flags:
  feature2: true
  feature3: true

scheduler:
  bill_generation: "45 546 22 ff"
  account_state: "6 6ff4 8f"

nested:
  level1:
    level11: 34t3gcw34
  level2:
    level21: 11
  level3:
    level31:
      level311: 678uhbrzs
