flags:
  feature1: false
  feature2: true
  feature3: false

scheduler:
  bill_generation: "45 546 22 ff"
  account_state: "6 6ff4 8f"

nested:
  level1:
    level11: 244
  level2:
    level21: 11
  level3:
    level31:
      level311: 22dxsa
