flags:
  feature1: false
  feature2: true
  feature3: false

scheduler:
  bill_generation: "45 546 22 ff"
  account_state: 13.56

nested:
  level1:
    level11: 34t3gcw34
  level2:
    level21: 11
  level3:
    level31:
      level311: 678uhbrzs
