name: Create Release Branch

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-branch:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if Release Branch Exists
        run: |
          branch_name=release_$(date +'%Y%m%d')
          echo $branch_name        

          if [ git show-ref --quiet refs/heads/$branch_name -eq 0 ]
          then
            echo "$branch_name branch found, So not creating branch"
          else
            echo "$branch_name branch not found, Creating branch"
            git switch -c "$branch_name"
            git push origin $branch_name
          fi
